name: "linting and testing"

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test